---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-container
  template:
    metadata:
      labels:
        app: postgres-container
        tier: backend
    spec:
      containers:
        - name: postgres-container
          image: postgres:13-alpine
          env:
           - name: POSTGRES_USER
             valueFrom:
                secretKeyRef:
                  name: akvsecrets
                  key: POSTGRES_USER
           - name: POSTGRES_PASSWORD
             valueFrom:
                secretKeyRef:
                  name: akvsecrets
                  key: POSTGRES_PASSWORD
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: secrets-store01-inline
              mountPath: /mnt/secrets-store
              readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-sync

---
kind: Service
apiVersion: v1
metadata:
  name: postgres-cluster-ip-service
spec:
  type: LoadBalancer
  selector:
    app: postgres-container
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
