---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync
spec:
  provider: azure
  secretObjects:
    - data:
        - key: postgresuser
          objectName: postgresuser
        - key: postgrespassword
          objectName: postgrespassword
      secretName: akvsecrets
      type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: AKSKeyvaultt
    cloudName: AzurePublicCloud
    objects: |
      array:
        - |
          objectName: postgresuser       
          objectType: secret
          objectAlias: postgresuser      
        - |
          objectName: postgrespassword
          objectType: secret
          objectAlias: postgrespassword
    tenantId: 4c6f1364-8db1-4e57-95ef-b3cf7dd7d4c9
