---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync
spec:
  provider: azure
  secretObjects:
    - secretName: username
      type: Opaque
      data:
        - objectName: username
          key: username
    - secretName: password
      type: Opaque
      data:
        - objectName: password
          key: password
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: testproj-keyvaultt
    cloudName: AzurePublicCloud
    objects: |
      array:
        - |
          objectName: username       
          objectType: secret
          objectAlias: username      
        - |
          objectName: password
          objectType: secret
          objectAlias: password
    tenantId: 4c6f1364-8db1-4e57-95ef-b3cf7dd7d4c9
