---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync
spec:
  provider: azure
  secretObjects:
    - secretName: postgresuser
      type: Opaque
      data:
        - objectName: postgresuser
          key: postgresuser
    - secretName: postgrespassword
      type: Opaque
      data:
        - objectName: postgrespassword
          key: postgrespassword
        
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: AKSKeyvaultt
    cloudName: AzurePublicCloud
    objects: |
      array:
        - |
          objectName: postgresuser       
          objectType: secret
          objectAlias: postgresuser      
        - |
          objectName: postgrespassword
          objectType: secret
          objectAlias: postgrespassword
    tenantId: 4c6f1364-8db1-4e57-95ef-b3cf7dd7d4c9
