---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync
spec:
  provider: azure
  secretObjects:
    - data:
        - key: POSTGRES_USER
          objectName: POSTGRES_USER
        - key: POSTGRES_PASSWORD
          objectName: POSTGRES_PASSWORD
      secretName: akvsecrets
      type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: AKSKeyvaultt
    cloudName: AzurePublicCloud
    objects: |
      array:
        - |
          objectName: postgresuser       
          objectType: secret
          objectAlias: POSTGRES_USER      
        - |
          objectName: postgrespassword
          objectType: secret
          objectAlias: POSTGRES_PASSWORD
    tenantId: 4c6f1364-8db1-4e57-95ef-b3cf7dd7d4c9
